### ISSUE TITLE
Elements must have their visible text as part of their accessible name

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_step_by_step#66]
`<button class="step-show" aria-expanded="false" aria-label="Show Find out what support we offer summary">Show step summary</button>`

Our "Show step summary" buttons have aria-labels such as "Show Find out what support we offer summary".

The aria-label overrides the visible text as a label, meaning someone using voice-driven navigation may find it hard to know the name of this button. 

We probably want to rework this to be something like:

<button class="step-show" aria-expanded="false">Show step summary <span class="visually-hidden">for Find out what support we offer </span></button>

**Comment by andybroomfield** [comment]
Is there a reason we have them different (Adding the show / hide). 
We could just remove the aria-label entierly.

**Comment by msayoung** [comment]
@Mjeffbrown  reports that SiteImprove reports:

Visible label and accessible label name do not match

 It's picking up the "show/hide step summary" of the step by step navigation (as the accessible name is "show/hide <page name> summary) - Could that be fixed by making the accessible label "Show/hide step summary for <page name>"?

**Comment by msayoung** [comment]
> Is there a reason we have them different (Adding the show / hide).
> We could just remove the aria-label entierly.

Ideally each button / link would have a unique accessible name. 

![screenshot of first bit of a step by step nav with 1: find out what support we offer in large bold letters and an underlined link below reading Show step summary](https://user-images.githubusercontent.com/3852805/225880265-43cc790c-83c6-4356-b83c-d4ab29cb4a7b.png)

But it would be more elegant perhaps for the visible label to be:

**Show step {step_number} summary** 
eg 

**Show step 1 summary** 

Then we could remove the aria altogether...
